// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.data.AdDbConection;

#nullable disable

namespace Web.data.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20230218135738_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web.data.model.Kompaniya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kompaniyalar");
                });

            modelBuilder.Entity("Web.data.model.Mashina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kompaniya_Id")
                        .HasColumnType("int");

                    b.Property<string>("modei")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rangi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("yili")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Kompaniya_Id");

                    b.ToTable("Mashinalar");
                });

            modelBuilder.Entity("Web.data.model.Mashina", b =>
                {
                    b.HasOne("Web.data.model.Kompaniya", "Kompaniya")
                        .WithMany("mashinalar")
                        .HasForeignKey("Kompaniya_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kompaniya");
                });

            modelBuilder.Entity("Web.data.model.Kompaniya", b =>
                {
                    b.Navigation("mashinalar");
                });
#pragma warning restore 612, 618
        }
    }
}
